- name: Install and run nginx
  hosts: web
  become: yes      # -b ante sudo {root user}
  tasks:
  - name: install nginx
    ansible.builtin.package:
    name: nginx
    state: present
  - name: start nginx
    ansible.builtin.service:
    name: nginx
    state: present
    enabled: yes

